import { useEffect, useMemo, useState } from 'react'
import './App.css'

type View = 'Home' | 'Matches' | 'Money map' | 'Privacy'
type Mode = 'Parent' | 'Tutor' | 'Learner'
type Tutor = { name: string; subject: string; school: string; rating: string; sessions: number; tone: string; initials: string }

const tutors: Tutor[] = [
  { name: 'Maya Chen', subject: 'Maths', school: 'Northview Academy', rating: '4.9', sessions: 42, tone: 'coral', initials: 'MC' },
  { name: 'Noah Williams', subject: 'Reading', school: 'East Ridge High', rating: '4.8', sessions: 28, tone: 'mint', initials: 'NW' },
  { name: 'Sofia Patel', subject: 'Science', school: 'Lakeside Collegiate', rating: '5.0', sessions: 35, tone: 'yellow', initials: 'SP' },
]

function App() {
  const [view, setView] = useState<View>('Home')
  const [mode, setMode] = useState<Mode>('Parent')
  const [query, setQuery] = useState('')
  const [online, setOnline] = useState(navigator.onLine)
  const [profile, setProfile] = useState(() => localStorage.getItem('pmfk-profile') || 'Avery')
  const [saved, setSaved] = useState(false)
  useEffect(() => {
    const update = () => setOnline(navigator.onLine)
    window.addEventListener('online', update); window.addEventListener('offline', update)
    return () => { window.removeEventListener('online', update); window.removeEventListener('offline', update) }
  }, [])
  const matches = useMemo(() => {
    const term = query.toLowerCase().trim()
    return term ? tutors.filter((tutor) => `${tutor.name} ${tutor.subject} ${tutor.school}`.toLowerCase().includes(term)) : tutors
  }, [query])
  const saveProfile = () => { localStorage.setItem('pmfk-profile', profile); setSaved(true); window.setTimeout(() => setSaved(false), 1600) }

  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">pmfk</div><div><strong>pmfk</strong><small>learn. earn. grow.</small></div></div><div className="profile-switcher"><Avatar text={profile[0]} tone="coral" /><div><b>{profile}'s family</b><span>Local account</span></div></div><nav>{(['Home', 'Matches', 'Money map', 'Privacy'] as View[]).map((item) => <button className={view === item ? 'nav-item active' : 'nav-item'} onClick={() => setView(item)} key={item}><span>{item === 'Home' ? '⌂' : item === 'Matches' ? '✦' : item === 'Money map' ? '◌' : '⌾'}</span>{item}</button>)}</nav><div className="sidebar-bottom"><div className="offline-note"><i className={online ? 'online-dot' : 'offline-dot'} />{online ? 'Synced just now' : 'Offline mode'}<small>Your data stays on this device</small></div><div className="made-by">Made by <b>Shawn Kong</b></div></div></aside>
    <section className="workspace"><header className="topbar"><span>Workspace <b>/</b> <strong>{view}</strong></span><div><small className="sync-pill">● {online ? 'All changes saved' : 'Working offline'}</small><button className="top-user"><Avatar text={profile[0]} tone="coral" />{profile}⌄</button></div></header><div className="content">
      {view === 'Home' && <Home profile={profile} mode={mode} setMode={setMode} setView={setView} />}
      {view === 'Matches' && <Matches query={query} setQuery={setQuery} matches={matches} />}
      {view === 'Money map' && <MoneyMap profile={profile} setProfile={setProfile} saveProfile={saveProfile} saved={saved} />}
      {view === 'Privacy' && <Privacy online={online} />}
    </div></section>
  </main>
}

function Avatar({ text, tone }: { text: string; tone: string }) { return <span className={`avatar ${tone}`}>{text.toUpperCase()}</span> }
function Home({ profile, mode, setMode, setView }: { profile: string; mode: Mode; setMode: (mode: Mode) => void; setView: (view: View) => void }) { return <><div className="welcome-row"><div><p className="eyebrow">Tuesday, September 23, 2026 <em>☼</em></p><h1>A little progress<br /><i>goes a long way.</i></h1><p className="intro">One calm place for your family to learn, earn, and grow together.</p></div><div className="mode-control"><span>Viewing as</span><div>{(['Parent', 'Tutor', 'Learner'] as Mode[]).map((item) => <button className={mode === item ? 'selected' : ''} onClick={() => setMode(item)} key={item}>{item}</button>)}</div></div></div><section className="focus-banner"><div><span className="label">THIS WEEK'S FOCUS</span><h2>Build a saving habit</h2><p>{profile} is <b>$3.50 away</b> from their skateboard goal.</p><button className="text-button" onClick={() => setView('Money map')}>View money map →</button></div><div className="goal-ring"><strong>82%</strong><small>saved</small></div></section><div className="section-heading"><div><span className="eyebrow">YOUR FAMILY</span><h2>Good things are growing</h2></div><button className="outline-button" onClick={() => setView('Money map')}>Open family view ↗</button></div><div className="dashboard-grid"><Stat tone="coral-card" title="Learning streak" value="6" unit="days" detail="↑ 2 days from last week" /><Stat tone="mint-card" title="Saved this month" value="$46" unit=".50" detail="↑ 18% from last month" /><Stat tone="yellow-card" title="Next session" value="4:30" unit="PM" detail="with Maya Chen · Maths" /></div><div className="lower-grid"><section><div className="panel-heading"><div><span className="eyebrow">FOR YOU</span><h2>Thoughtful matches</h2></div><button className="plain-button" onClick={() => setView('Matches')}>See all →</button></div><p className="panel-subtitle">Local tutors recommended for {profile}'s learning goals.</p>{tutors.slice(0, 2).map((tutor) => <TutorRow tutor={tutor} onSelect={() => setView('Matches')} key={tutor.name} />)}</section><section className="activity-panel"><div className="panel-heading"><div><span className="eyebrow">AT A GLANCE</span><h2>Family activity</h2></div></div><p className="activity">✓ <b>Session completed</b><small>Maths with Maya Chen · Today</small></p><p className="activity">$ <b>Weekly allowance added</b><small>+$10.00 to {profile}'s wallet · Mon</small></p><p className="activity">✦ <b>New goal created</b><small>Skateboard fund · Sun</small></p></section></div></> }
function Stat({ tone, title, value, unit, detail }: { tone: string; title: string; value: string; unit: string; detail: string }) { return <article className={`stat-card ${tone}`}><span>{title}</span><strong>{value}<small>{unit}</small></strong><p>{detail}</p><div className="stat-line" /></article> }
function TutorRow({ tutor, onSelect }: { tutor: Tutor; onSelect: () => void }) { return <button className="tutor-row" onClick={onSelect}><Avatar text={tutor.initials} tone={tutor.tone} /><span><b>{tutor.name}</b><small>{tutor.subject} · {tutor.school}</small></span><i>★ {tutor.rating}<small>{tutor.sessions} sessions</small></i><strong>↗</strong></button> }
function Matches({ query, setQuery, matches }: { query: string; setQuery: (value: string) => void; matches: Tutor[] }) { return <div className="page-view"><div className="page-title"><div><span className="eyebrow">ON-DEVICE MATCHING</span><h1>Find a good fit.</h1><p>PMFK's private helper finds nearby tutors using only the preferences you choose.</p></div><div className="ai-badge">✦ <small>PMFK helper<br /><b>Ready to help</b></small></div></div><div className="search-wrap">⌕<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by subject, name, or school" /></div><div className="match-layout"><div><p className="result-heading"><b>{matches.length} thoughtful matches</b><span>Sorted by learning fit</span></p>{matches.map((tutor) => <div className="match-card" key={tutor.name}><TutorRow tutor={tutor} onSelect={() => undefined} /><p>✦ {tutor.name.split(' ')[0]} is a strong fit because they teach {tutor.subject.toLowerCase()} and have experience with younger learners.</p></div>)}{matches.length === 0 && <div className="empty-state">No matches yet. Try Maths or Reading.</div>}</div><aside className="helper-card"><span className="eyebrow">PRIVATE HELPER</span><h2>Good decisions,<br /><i>made simpler.</i></h2><p>Your preferences stay on your device. No ad network and no API key needed.</p><b>✓ No paid upgrade</b><b>✓ Works offline</b><b>✓ Family-first privacy</b></aside></div></div> }
function MoneyMap({ profile, setProfile, saveProfile, saved }: { profile: string; setProfile: (value: string) => void; saveProfile: () => void; saved: boolean }) { return <div className="page-view"><div className="page-title"><div><span className="eyebrow">FAMILY MONEY MAP</span><h1>Small steps, clearly seen.</h1><p>Set a simple goal and keep the conversation about money open and kind.</p></div><button className="coral-button" onClick={saveProfile}>{saved ? 'Saved locally ✓' : 'Save changes'}</button></div><div className="money-layout"><section><div className="big-goal"><span className="eyebrow">{profile.toUpperCase()}'S ACTIVE GOAL</span><h2>Skateboard fund</h2><p>Target date · November 14, 2026</p><strong>$46.50 <small>of $60</small></strong><div className="large-progress" /></div><div className="money-columns"><b>Allowance this week<strong>$10.00</strong><small>Next on Friday</small></b><b>Learning rewards<strong>$6.50</strong><small>2 rewards earned</small></b><b>Giving jar<strong>$4.00</strong><small>Ready to share</small></b></div></section><aside className="settings-card"><span className="eyebrow">LOCAL PROFILE</span><h2>Who is this for?</h2><label>Display name<input value={profile} onChange={(event) => setProfile(event.target.value)} /></label><p>Stored in this account on this device. A parent can change or remove it any time.</p></aside></div></div> }
function Privacy({ online }: { online: boolean }) { return <div className="page-view"><div className="page-title"><div><span className="eyebrow">TRUST CENTRE</span><h1>Privacy, in plain language.</h1><p>PMFK is designed around a parent's right to understand and control their family's information.</p></div><span className="privacy-status">● {online ? 'Synced privately' : 'Offline and private'}</span></div><div className="privacy-grid"><article><b>01</b><h2>Private by design</h2><p>Public profiles use a chosen name and icon only. Guardian details and family records stay in a separate account area.</p><strong>Identity stays with the family.</strong></article><article><b>02</b><h2>Location is ephemeral</h2><p>Check-ins calculate the safe-zone result on the device. PMFK keeps only inside or outside, never a movement history.</p><strong>We remember the result, not the route.</strong></article><article><b>03</b><h2>Control and erasure</h2><p>A parent can close an account and request deletion. Adult learner profiles can be scrubbed while required accounting records remain anonymous.</p><strong>Your account is yours.</strong></article><article className="privacy-wide"><div><span className="eyebrow">DEVICE STATUS</span><h2>Ready for offline use</h2><p>Core family views and saved changes work without a network. Reconnect to sync securely.</p></div><div><p>✓ Local data saved</p><p>✓ No API key required</p><p>✓ No paid tier</p></div></article></div></div> }

export default App
